### ISSUE TITLE
Linux installation mongodb no public key

### ISSUE THREAD

**Issue by henrywhitaker3** [MediaButler/Issues#2]
Consider adding: `sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4` to the wiki for linux install to add the public key for the mongodb repo otherwise `sudo apt update` will fail (command to add the public key pulled from [here](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/))

**Comment by vertig0ne** [comment]
Wiki has been updated to reflect this. Thank you for bringing this to our attention.
